# Generated by Django 6.0.3 on 2026-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenselineitem",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
