# Generated by Django 6.0.3 on 2026-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_expenselineitem_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenselineitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
