# Generated by Django 6.0.3 on 2026-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_expenselineitem_amount"),
        ("payment", "0020_alter_generalexpense_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="invoices",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="payment.invoice"
            ),
        ),
    ]
