# Generated by Django 6.0.3 on 2026-09-19 14:23

from django.db import migrations


def move_invoices(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        if event.invoice:
            event.invoices.add(event.invoice)


def reverse_move_invoices(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        first_invoice = event.invoices.first()
        if first_invoice:
            event.invoice = first_invoice
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_invoices"),
    ]

    operations = [
        migrations.RunPython(move_invoices, reverse_move_invoices),
    ]
