# Generated by Django 6.0.3 on 2026-09-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_migrate_invoices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="invoice",
        ),
    ]
