# Generated by Django 6.0.3 on 2026-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
