# Generated by Django 6.0.3 on 2026-03-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
