# Generated by Django 6.0.3 on 2026-03-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_price_per_hour_product_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
