# Generated by Django 6.0.3 on 2026-03-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_bookingitemunit_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_per_day',
        ),
    ]
