# Generated by Django 6.0.3 on 2026-03-23 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_productunit_qty_tracking'),
        ('users', '0007_client_created_by_client_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='users.organization'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_booking_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingitemunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_item_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingitemunit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_item_units', to='users.organization'),
        ),
        migrations.AddField(
            model_name='bookingitemunit',
            name='quantity_returned_damaged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingitemunit',
            name='quantity_returned_good',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingitemunit',
            name='quantity_returned_in_damaged_condition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingitemunit',
            name='quantity_returned_in_good_condition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingitemunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_booking_item_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='users.organization'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('returned', 'Returned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
