# Generated by Django 6.0.3 on 2026-03-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_bookingitemunit_quantity_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitemunit',
            name='quantity_returned',
        ),
    ]
