# Generated by Django 6.0.3 on 2026-03-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20260323_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitemunit',
            name='quantity_returned_in_damaged_condition',
        ),
        migrations.RemoveField(
            model_name='bookingitemunit',
            name='quantity_returned_in_good_condition',
        ),
    ]
