# Generated by Django 6.0.3 on 2026-08-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_bookingitemunit_quantity_returned_damaged_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="event_name",
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_title",
            field=models.CharField(default="Untitled Booking", max_length=255),
            preserve_default=False,
        ),
    ]
