# Generated by Django 6.0.3 on 2026-09-22 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_remove_booking_event_name_booking_booking_title"),
        ("users", "0028_globalconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="country",
            field=models.CharField(
                choices=[
                    ("Nigeria", "Nigeria"),
                    ("Kenya", "Kenya"),
                    ("Rwanda", "Rwanda"),
                    ("USA", "USA"),
                    ("UK", "UK"),
                ],
                default="Nigeria",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="event_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="note_for_org",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="set_down_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="setup_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="available_for_rental",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OrganizationBookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_days",
                    models.JSONField(
                        default=list,
                        help_text='List of available days, e.g., ["Monday", "Tuesday"]',
                    ),
                ),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("is_accepting_requests", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_settings",
                        to="users.organization",
                    ),
                ),
            ],
        ),
    ]
