# Generated by Django 6.0.3 on 2026-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_booking_address_booking_city_booking_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationbookingsettings",
            name="public_url_slug",
            field=models.SlugField(
                blank=True,
                help_text="Custom slug for public marketplace URL",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("request", "Request"),
                    ("confirmed", "Confirmed"),
                    ("picked_up", "Picked Up"),
                    ("returned", "Returned"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="request",
                max_length=20,
            ),
        ),
    ]
