# Generated by Django 6.0.3 on 2026-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_organizationbookingsettings_public_url_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationbookingsettings",
            name="storefront_name",
            field=models.CharField(
                blank=True,
                help_text="Custom name for the storefront",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="productunit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_units/"),
        ),
    ]
