# Generated by Django 6.0.3 on 2026-09-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_organizationbookingsettings_storefront_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="last_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("request", "Request"),
                    ("processed", "Processed"),
                    ("confirmed", "Confirmed"),
                    ("picked_up", "Picked Up"),
                    ("returned", "Returned"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="request",
                max_length=20,
            ),
        ),
    ]
