# Generated by Django 6.0.3 on 2026-04-30 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_bookingitemunit_quantity_returned_in_damaged_condition_and_more'),
        ('notification', '0004_notification_created_by_notification_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.booking'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_picked_up', 'Booking Picked Up'), ('booking_returned', 'Booking Returned'), ('payment_received', 'Payment Received'), ('inventory_low', 'Inventory Low')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
