# Generated by Django 6.0.3 on 2026-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_invoicelineitem_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
