# Generated by Django 6.0.3 on 2026-07-14 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_invoice_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
