# Generated by Django 6.0.3 on 2026-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0016_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="event_date",
            field=models.DateTimeField(
                blank=True, help_text="The date of the event/job", null=True
            ),
        ),
    ]
