# Generated by Django 6.0.3 on 2026-07-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_bookingitemunit_quantity_returned_damaged_and_more"),
        ("payment", "0017_invoice_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="inventory.booking",
            ),
        ),
    ]
