# Generated by Django 6.0.3 on 2026-09-22 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_booking_address_booking_city_booking_country_and_more"),
        ("payment", "0020_alter_generalexpense_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="inventory.booking",
            ),
        ),
    ]
