# Generated by Django 6.0.3 on 2026-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, default='#7c3aed', help_text='Hex color code for invoices and branding', max_length=7, null=True),
        ),
    ]
