# Generated by Django 6.0.3 on 2026-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_inventory_booking_per_month',
            field=models.IntegerField(default=10, help_text='Set to -1 for unlimited.'),
        ),
    ]
