# Generated by Django 6.0.3 on 2026-06-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subscriptionplan_has_inventory_and_more'),
    ]

def seed_free_plan_and_organizations(apps, schema_editor):
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')
    Organization = apps.get_model('users', 'Organization')
    Subscription = apps.get_model('users', 'Subscription')

    # Create or get the free plan
    free_plan, created = SubscriptionPlan.objects.get_or_create(
        is_free=True,
        defaults={
            'name': 'Free',
            'description': 'Basic free tier with limited resources',
            'price': 0.0,
            'billing_cycle': 'monthly',
            'max_invoices_per_month': 10,
            'max_inventory_booking_per_month': 10,
            'has_booking': True,
            'has_invoice': True,
            'is_active': True,
        }
    )

    # Set all existing organizations to have this free plan
    # Since plan_name is a string in Subscription, we set it to 'Free'
    # And we update max_invoices_per_month to match
    for org in Organization.objects.all():
        if hasattr(org, 'subscription'):
            sub = org.subscription
            sub.plan_name = 'Free'
            sub.max_invoices_per_month = free_plan.max_invoices_per_month
            sub.save()
        else:
            Subscription.objects.create(
                organization=org,
                plan_name='Free',
                max_invoices_per_month=free_plan.max_invoices_per_month
            )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_subscriptionplan_has_inventory_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_free_plan_and_organizations),
    ]
