# Generated by Django 6.0.3 on 2026-06-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_seed_free_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='has_inventory',
            new_name='has_booking',
        ),
    ]
