# Generated by Django 6.0.3 on 2026-07-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_subscriptionplan_has_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="swift_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
