# Generated by Django 6.0.3 on 2026-07-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_remove_client_company_name_remove_client_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="client_logos/"),
        ),
    ]
