# Generated by Django 6.0.3 on 2026-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('validator', 'Validator'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
