# Generated by Django 6.0.3 on 2026-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("business", "Business"), ("individual", "Individual")],
                default="business",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
