# Generated by Django 6.0.3 on 2026-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_client_client_type_client_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="users.organization"
            ),
        ),
    ]
