# Generated by Django 6.0.3 on 2026-09-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_role_organizationmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_tier_monthly_quota",
                    models.IntegerField(
                        default=10,
                        help_text="Default monthly invoice/booking quota for free users.",
                    ),
                ),
                (
                    "max_organizations_per_user",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of businesses a single user can create.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Configuration",
                "verbose_name_plural": "Global Configuration",
            },
        ),
    ]
