# Generated by Django 6.0.3 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_globalconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
