# Generated by Django 6.0.3 on 2026-08-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackanswer_answer_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackquestion',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
