# Generated by Django 6.0.3 on 2026-08-01 21:50

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedbackquestion_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeedback',
            name='public_id',
            field=models.CharField(default=feedback.models.generate_short_id, editable=False, max_length=50, unique=True),
        ),
    ]
